import os

LINUX_AUTH_LOG_PATH = "/var/log/auth.log"  #default
CPU_USAGE_THRESHOLD = 85.0     
CPU_USAGE_BY_CORE_THRESHOLD = 95.0
CPU_FREQUENCY_THRESHOLD = 5
CPU_IOWAIT_THRESHOLD = 20.0
RAM_USAGE_THRESHOLD = 85.0 
DISK_USAGE_READ_THRESHOLD = 100 #MB/s
DISK_USAGE_WRITE_THRESHOLD = 100 #MB/s
MAX_FAILED_ATTEMPS_SSH = 10 
TIME_WINDOW = 60
CHECK_INTERVAL_SECONDS = 2
RISK_SCORE_THRESHOLD = 50